name: rezssZombieWave
main: io.github.rezssZombieWave.RezssMain
version: 0.01
commands:
  rezss:
    description: This is a demo command.
    usage: /<command> [player]
    permissions: <plugin name>.basic
    permission-message: You don't have <permission>
